use shop_axm;


CREATE TABLE IF NOT EXISTS users(

id BIGINT UNSIGNED  NOT NULL AUTO_INCREMENT PRIMARY KEY,
firstname   VARCHAR(100) NOT NULL,
lastname   VARCHAR(100) NOT NULL,
email   VARCHAR(100) NOT NULL,
password   VARCHAR(100) NOT NULL,
phone  VARCHAR(100) DEFAULT NUll,
title   VARCHAR(100) DEFAULT NULL,
bio   VARCHAR(100) DEFAULT NULL,
image_url   VARCHAR(100) DEFAULT NULL,
enabled   BOOLEAN DEFAULT TRUE,
is_not_locked BOOLEAN DEFAULT TRUE,
is_using_mfa BOOLEAN DEFAULT FALSE,
created_at DATE DEFAULT CURRENT_DATE
);

CREATE TABLE IF NOT EXISTS roles(
id BIGINT UNSIGNED  NOT NULL AUTO_INCREMENT PRIMARY KEY,
name   VARCHAR(100) NOT NULL,
permission   VARCHAR(100) NOT NULL
);


CREATE TABLE IF NOT EXISTS users_roles(
id BIGINT UNSIGNED  NOT NULL AUTO_INCREMENT PRIMARY KEY,
user_id  BIGINT UNSIGNED NOT NULL,
role_id BIGINT UNSIGNED NOT NULL,
FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE,
FOREIGN KEY (role_id) REFERENCES roles(id) ON DELETE CASCADE ON UPDATE CASCADE
);



CREATE TABLE IF NOT EXISTS products(
id                BIGINT UNSIGNED  NOT NULL AUTO_INCREMENT PRIMARY KEY,
name              VARCHAR(100)     NOT NULL,
product_code       VARCHAR(100)    NOT NULL,
intern_prod_code   VARCHAR(100)    DEFAULT NULL,
qr_code_data        VARCHAR(100)  DEFAULT NULL,
description         VARCHAR(255)  DEFAULT NULL,
main_image           VARCHAR(255)  DEFAULT NULL,
price                DECIMAL(7,2)  NOT NULL,
cost_price            DECIMAL(7,2) DEFAULT NULL,
markup_percentage     DECIMAL(3,2)  DEFAULT NULL,
stock            INT NOT NULL,
is_available BOOLEAN DEFAULT TRUE,
warranty_months INT DEFAULT NULL,
vat_percentage INT DEFAULT NULL,
CONSTRAINT UQ_Products_Product_Code UNIQUE(product_code)
);